defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= ENV['POSTGRES_USERNAME'] || ENV['USER'] %>

development:
  database: delivergram_dev
  <<: *defaults

test:
  database: delivergram_test
  <<: *defaults

staging:
  database: delivergram_staging
  <<: *defaults

production:
  database: delivergram_prod
  <<: *defaults

